name: jobpulseai_mobile
description: JobPulseAI Mobile - Career Intelligence
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.0.7
  file_picker: 10.3.8
  provider: ^6.1.1
  path_provider: ^2.1.2
  intl: ^0.20.3
  path: ^1.9.1
  logger: ^2.0.0
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true